### ISSUE TITLE
rosinstall_generator time machine workflow

### ISSUE THREAD

**Issue by gavanderhoorn** [gavanderhoorn/rosin_bug_hunt_l3#2]
```shell
mkdir /tmp/some_scratch_dir && cd /tmp/some_scratch_dir

# setup venv with needed tools
python3 -m venv --without-pip ritm_venv
. ritm_venv/bin/activate
curl https://bootstrap.pypa.io/get-pip.py | python3

# use custom version of rosdistro scripts
pip3 install 'git+https://github.com/gavanderhoorn/rosdistro_python.git@rosin_bughunt_0.6.8'
pip3 install rosinstall_generator

# get a copy of the rosdistro db
git clone https://github.com/ros/rosdistro.git

# go back to some point in time.
# If you know the commit, check it out directly.
# if you don't, but have a date, use something like:
#  git -C rosdistro checkout `git -C rosdistro rev-list -n 1 --before="2016-04-02 01:00 GMT+2" master`
#
# here in this example we just go back to 5000 commits before current HEAD
git -C rosdistro checkout HEAD~5000

# update the rosdistro cache
# this will hang a few times, asking for 'github' password (terraranger repos),
# just press enter 'til it continues
# note: add '--debug' for more info
rosdistro_build_cache --ignore-local --ignore-errors rosdistro/index.yaml indigo

# TODO: this is quite resource intensive, and can take quite some time,
# depending on how far back we've gone (because of increased cache misses)

# update rosdistro db cache entries with the just generated one
sed -i "s|http://repositories.ros.org/rosdistro_cache|file://`pwd`|g" rosdistro/index.yaml

# alternatively: replace rosdistro/index.yaml with a minimal one for the
#                $ROS_VERSION we're targetting and no other entries

# make rosinstall_generator use rosdistro from the past
ROSDISTRO_INDEX_URL=file://`pwd`/rosdistro/index.yaml \
  rosinstall_generator \
  fanuc_driver \
  --rosdistro=indigo \
  --deps \
  --tar > fanuc_driver.rosinstall
```

**Comment by gavanderhoorn** [comment]
@ChrisTimperley: literally 5 mins after we discussed my failure I got it to work.

I'll probably automate this a bit further (probably an extension to `rosinstall_generator` making it accept `rosdistro` commit hashes / dates or something, like your script).

This should already work though. Could I bother you to see whether the above instructions also work for you?

**Comment by gavanderhoorn** [comment]
It makes sense to re-use the cache as much as possible when going back even further. Suffixing cache files with the commit they were created for would make this manageable.

The fewer cache misses, the fewer times `rosdistro_build_cache` has to reach out to the VCS the release artefacts are stored in.

I feel that would be beneficial.

**Comment by gavanderhoorn** [comment]
I still have to address the issue of `rosdistro_build_cache` stalling whenever it encounters a package that was hosted in a repository that no longer exists / has been made private (ie: requires authentication).

Deep down, `rosdistro` directly calls `git ls-remote ..` ([here](https://github.com/ros-infrastructure/rosdistro/blob/efcaaa46ffae16b450849c4f3a147bc60aac8cb1/src/rosdistro/repository_specification.py#L71)), and that is prompting me for a username/pw combo. Haven't found a way around that yet, unfortunately. Perhaps replacing that with a suitable Python git API that allows us to disable / circumvent that could help, but not sure.

**Comment by ChrisTimperley** [comment]
@gavanderhoorn, perhaps you could use [GitPython](https://github.com/gitpython-developers/GitPython)? The documentation isn't great but it's a fairly capable tool.

To deal with renaming, I was thinking of having the user supply a mapping between old and new repository URLs -- there's a bit of manual work involved but it shouldn't be too much.

**Comment by ChrisTimperley** [comment]
Here's the contents of the `fanuc_driver.rosinstall` that I produced by following your instructions:

```
- tar:
    local-name: actionlib
    uri: https://github.com/ros-gbp/actionlib-release/archive/release/indigo/actionlib/1.11.5-0.tar.gz
    version: actionlib-release-release-indigo-actionlib-1.11.5-0
- tar:
    local-name: catkin
    uri: https://github.com/ros-gbp/catkin-release/archive/release/indigo/catkin/0.6.18-0.tar.gz
    version: catkin-release-release-indigo-catkin-0.6.18-0
- tar:
    local-name: class_loader
    uri: https://github.com/ros-gbp/class_loader-release/archive/release/indigo/class_loader/0.3.3-1.tar.gz
    version: class_loader-release-release-indigo-class_loader-0.3.3-1
- tar:
    local-name: cmake_modules
    uri: https://github.com/ros-gbp/cmake_modules-release/archive/release/indigo/cmake_modules/0.3.3-0.tar.gz
    version: cmake_modules-release-release-indigo-cmake_modules-0.3.3-0
- tar:
    local-name: common_msgs/actionlib_msgs
    uri: https://github.com/ros-gbp/common_msgs-release/archive/release/indigo/actionlib_msgs/1.11.9-0.tar.gz
    version: common_msgs-release-release-indigo-actionlib_msgs-1.11.9-0
- tar:
    local-name: common_msgs/geometry_msgs
    uri: https://github.com/ros-gbp/common_msgs-release/archive/release/indigo/geometry_msgs/1.11.9-0.tar.gz
    version: common_msgs-release-release-indigo-geometry_msgs-1.11.9-0
- tar:
    local-name: common_msgs/sensor_msgs
    uri: https://github.com/ros-gbp/common_msgs-release/archive/release/indigo/sensor_msgs/1.11.9-0.tar.gz
    version: common_msgs-release-release-indigo-sensor_msgs-1.11.9-0
- tar:
    local-name: common_msgs/trajectory_msgs
    uri: https://github.com/ros-gbp/common_msgs-release/archive/release/indigo/trajectory_msgs/1.11.9-0.tar.gz
    version: common_msgs-release-release-indigo-trajectory_msgs-1.11.9-0
- tar:
    local-name: control_msgs
    uri: https://github.com/ros-gbp/control_msgs-release/archive/release/indigo/control_msgs/1.3.1-0.tar.gz
    version: control_msgs-release-release-indigo-control_msgs-1.3.1-0
- tar:
    local-name: fanuc/fanuc_driver
    uri: https://github.com/ros-industrial-release/fanuc-release/archive/release/indigo/fanuc_driver/0.4.0-1.tar.gz
    version: fanuc-release-release-indigo-fanuc_driver-0.4.0-1
- tar:
    local-name: gencpp
    uri: https://github.com/ros-gbp/gencpp-release/archive/release/indigo/gencpp/0.5.4-0.tar.gz
    version: gencpp-release-release-indigo-gencpp-0.5.4-0
- tar:
    local-name: genlisp
    uri: https://github.com/ros-gbp/genlisp-release/archive/release/indigo/genlisp/0.4.15-0.tar.gz
    version: genlisp-release-release-indigo-genlisp-0.4.15-0
- tar:
    local-name: genmsg
    uri: https://github.com/ros-gbp/genmsg-release/archive/release/indigo/genmsg/0.5.7-0.tar.gz
    version: genmsg-release-release-indigo-genmsg-0.5.7-0
- tar:
    local-name: genpy
    uri: https://github.com/ros-gbp/genpy-release/archive/release/indigo/genpy/0.5.8-0.tar.gz
    version: genpy-release-release-indigo-genpy-0.5.8-0
- tar:
    local-name: industrial_core/industrial_msgs
    uri: https://github.com/ros-industrial-release/industrial_core-release/archive/release/indigo/industrial_msgs/0.4.3-0.tar.gz
    version: industrial_core-release-release-indigo-industrial_msgs-0.4.3-0
- tar:
    local-name: industrial_core/industrial_robot_client
    uri: https://github.com/ros-industrial-release/industrial_core-release/archive/release/indigo/industrial_robot_client/0.4.3-0.tar.gz
    version: industrial_core-release-release-indigo-industrial_robot_client-0.4.3-0
- tar:
    local-name: industrial_core/industrial_utils
    uri: https://github.com/ros-industrial-release/industrial_core-release/archive/release/indigo/industrial_utils/0.4.3-0.tar.gz
    version: industrial_core-release-release-indigo-industrial_utils-0.4.3-0
- tar:
    local-name: industrial_core/simple_message
    uri: https://github.com/ros-industrial-release/industrial_core-release/archive/release/indigo/simple_message/0.4.3-0.tar.gz
    version: industrial_core-release-release-indigo-simple_message-0.4.3-0
- tar:
    local-name: message_generation
    uri: https://github.com/ros-gbp/message_generation-release/archive/release/indigo/message_generation/0.2.10-0.tar.gz
    version: message_generation-release-release-indigo-message_generation-0.2.10-0
- tar:
    local-name: message_runtime
    uri: https://github.com/ros-gbp/message_runtime-release/archive/release/indigo/message_runtime/0.4.12-0.tar.gz
    version: message_runtime-release-release-indigo-message_runtime-0.4.12-0
- tar:
    local-name: pluginlib
    uri: https://github.com/ros-gbp/pluginlib-release/archive/release/indigo/pluginlib/1.10.2-0.tar.gz
    version: pluginlib-release-release-indigo-pluginlib-1.10.2-0
- tar:
    local-name: robot_model/urdf
    uri: https://github.com/ros-gbp/robot_model-release/archive/release/indigo/urdf/1.11.10-0.tar.gz
    version: robot_model-release-release-indigo-urdf-1.11.10-0
- tar:
    local-name: robot_model/urdf_parser_plugin
    uri: https://github.com/ros-gbp/robot_model-release/archive/release/indigo/urdf_parser_plugin/1.11.10-0.tar.gz
    version: robot_model-release-release-indigo-urdf_parser_plugin-1.11.10-0
- tar:
    local-name: ros/rosbuild
    uri: https://github.com/ros-gbp/ros-release/archive/release/indigo/rosbuild/1.11.12-0.tar.gz
    version: ros-release-release-indigo-rosbuild-1.11.12-0
- tar:
    local-name: ros/rosclean
    uri: https://github.com/ros-gbp/ros-release/archive/release/indigo/rosclean/1.11.12-0.tar.gz
    version: ros-release-release-indigo-rosclean-1.11.12-0
- tar:
    local-name: ros/roslang
    uri: https://github.com/ros-gbp/ros-release/archive/release/indigo/roslang/1.11.12-0.tar.gz
    version: ros-release-release-indigo-roslang-1.11.12-0
- tar:
    local-name: ros/roslib
    uri: https://github.com/ros-gbp/ros-release/archive/release/indigo/roslib/1.11.12-0.tar.gz
    version: ros-release-release-indigo-roslib-1.11.12-0
- tar:
    local-name: ros/rosunit
    uri: https://github.com/ros-gbp/ros-release/archive/release/indigo/rosunit/1.11.12-0.tar.gz
    version: ros-release-release-indigo-rosunit-1.11.12-0
```

**Comment by gavanderhoorn** [comment]
@ChrisTimperley wrote:
> @gavanderhoorn, perhaps you could use [GitPython](https://github.com/gitpython-developers/GitPython)? The documentation isn't great but it's a fairly capable tool.

yeah, I looked at that already, but some googling suggests it doesn't actually support something like `git ls-remote`. I'll take another look though.

> To deal with renaming, I was thinking of having the user supply a mapping between old and new repository URLs -- there's a bit of manual work involved but it shouldn't be too much.

It would need some more work on the `rosdistro_build_cache` side, but that could work.

Right now I just ignore them, but if the repositories that vanished are actually needed, a remap might allow us to continue.

**Comment by gavanderhoorn** [comment]
re: `.rosinstall`; yep, that is the expected contents.

Nice. Thanks for testing.

**Comment by wasowski** [comment]
This kind of makes sense, to the extent I understand what is going on (as really not a ROS dev).  I tried to repeat the same steps for https://github.com/ros/geometry2/pull/167/commits/1957a441092d0bd90f115924f54831657ac6161f (switched the date, instead of HEAD~5000, I selected the commit by date) and switched fanuc_driver to geometry2 in the last command. 

At that point I failed with the following problem:

> The following not released packages/stacks will be ignored: geometry2

The rosinstall file created is empty. I gather that tf2 was not released yet at that point (April 2, 2016).   should I just clone geometry2 to the working dir, aside rosdistro/, and try to build/test it as if it was a catking workspace?

**Comment by gavanderhoorn** [comment]
`geometry2` was definitely released at that point: for April 2, 2016 it would be between `0.5.13` and `0.5.14` (see [ros/geometry2/releases](https://github.com/ros/geometry2/releases)).

Perhaps something else is not working as it should? If `rosinstall_generator` complains a pkg isn't released, that would suggest it can't find it in the `distribution.yaml`. Can you check that the pkg is listed?

**Comment by wasowski** [comment]
While checking distribution.yaml, let me share that I used this line
> rosdistro_build_cache --ignore-local --ignore-errors rosdistro/index.yaml indigo
literally. 

But is indigo the right distro?

**Comment by wasowski** [comment]
rosdistro/indigo/distribution.yaml has this

```yaml
geometry2:
    doc:
      type: git
      url: https://github.com/ros/geometry2.git
      version: indigo-devel
    release:
      packages:
      - geometry_experimental
      - tf2
      - tf2_bullet
      - tf2_eigen
      - tf2_geometry_msgs
      - tf2_kdl
      - tf2_msgs
      - tf2_py
      - tf2_ros
      - tf2_sensor_msgs
      - tf2_tools
      tags:
        release: release/indigo/{package}/{version}
      url: https://github.com/ros-gbp/geometry2-release.git
      version: 0.5.13-0
    source:
      test_pull_requests: true
      type: git
      url: https://github.com/ros/geometry2.git
      version: indigo-devel
    status: maintained
```
